---
usage: opensource
includes:
- lib
- test
- "../../support/mutant"
requires:
- mutant
- ruby_itblock
- minitest_coverage
- julewire-ractor
hooks:
- "../../support/mutant/zeitwerk_eager_load.rb"
integration:
  name: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
  - Julewire.enable_experimental_ractor!
  - Julewire.ractor
  - Julewire::Ractor*
